### ISSUE TITLE
Reduce back button top and bottom padding

### ISSUE THREAD

**Issue by NinaEmiko** [NinaEmiko/code-jawn#63]

**Comment by Helion-web** [comment]
Remove the padding tag from the script.

**Comment by Helion-web** [comment]
1. Remove the padding tag from the script.
2. Or if you cant do that depending on the script you are using.Try doing it with code: 

button{
padding : initial ;
}
**or**
<button style="padding:initial;"></button>
**or**
<style>
button{
padding:initial;
}
</style>

(depending on the way you are writing your css code.)This way if you have placed a padding into a button and you cant change it bcs it breaks the structure of the webpage or any other reason,you can use this to make the button go in the initial state.

**Comment by LolaaDiamondd** [comment]
no longer required
