### ISSUE TITLE
Update text answers

### ISSUE THREAD

**Issue by NinaEmiko** [NinaEmiko/code-jawn#78]
Some answers are text and not code. Those texts should not be formatted like code, so they need to be displayed with the AnswerText component instead of the AnswerCodeBlock component they are currently displayed with.

Affected answers:

Question 3, Answer 2
Question 4, Answer 1
Question 4, Answer 2
Question 4, Answer 3
Question 4, Answer 4

**Comment by LolaaDiamondd** [comment]
corrected answers, merged and deployed
